### ISSUE TITLE
Error with @font-face within media-queries

### ISSUE THREAD

**Issue by seriema** [gruntjs/grunt-contrib-csslint#12]
I'm getting several errors on this:

``` css
@media screen {
  @font-face {
    font-family: 'footable';
    src: url('fonts/footable.svg#myfont') format('svg');
    font-weight: normal;
    font-style: normal;
  }
}
```

The errors are:

```
Expected RBRACE at line 2, col 3. This rule looks for recoverable syntax errors. (errors)
Unexpected token '}' at line 8, col 1. This rule looks for recoverable syntax errors. (errors)
```

From what I've gathered, [this isn't valid CSS2](http://stackoverflow.com/a/7923567/703921) but is valid CSS3. So I guess it should be OK from a linting POV? Or maybe this isn't an issue for just `grunt-contrib-csslint`?
