### ISSUE TITLE
compatible-vendor-prefixes set to true fails for keyframes transform

### ISSUE THREAD

**Issue by franz-josef-kaiser** [gruntjs/grunt-contrib-csslint#61]
The block breaking CSSLint is

```scss
@keyframes spin {
  from {
    -moz-transform: rotate(10deg);
    -ms-transform: rotate(10deg);
    -webkit-transform: rotate(10deg);
    transform: rotate(10deg);
  }
  to {
    -moz-transform: rotate(360deg);
    -ms-transform: rotate(360deg);
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}
```

The error message is

```
Linting .cache/styles/style.css...ERROR
[GENERAL]
>> ERROR: Fatal error, cannot continue: Cannot read property 'push' of undefined undefined (undefined) Browsers: undefined
```

First I thought this might be a bug with having specified `0deg` as value, but this is *not* the case.

This issue is just here as reminder for others who run into this problem and haven't yet updated their version.

Affected version: `"grunt-contrib-csslint" : "^0.3.1"`. Fixed with 4504493

**Comment by sindresorhus** [comment]
I don't see the point of this. The first thing you should do when having a problem is upgrading to the latest version.

**Comment by franz-josef-kaiser** [comment]
@sindresorhus Normally every bug and change should have a ticket (or the project has an extensive changelog). This one had none, so I added one.

**Comment by franz-josef-kaiser** [comment]
And and btw, this is still present with the current version. When testing it (which I just did a minute ago), it still broke.  My mistake was that I deleted the lines for something other before upgrading.

**Comment by dangercris** [comment]
Hi @franz-josef-kaiser I have the same error, i upgrade to last versión but persist what is the solution?

**Comment by franz-josef-kaiser** [comment]
@dangercris IIRC it persists.

**Comment by chrisfrancis27** [comment]
Should we reopen this issue? I'm seeing it happen on the latest version (1.0.0). Adding a simple keyframe animation causes it to fail with the following:

```
[Lundefined:Cundefined]
>> ERROR: Fatal error, cannot continue: Cannot read property 'push' of undefined undefined (undefined) Browsers: undefined
```

I don't think it's the vendor prefixes as I only have this:

```css
@keyframes spin {
    0% { transform: rotate(0) },
    100% { transform: rotate(360deg) }
}
```

Bizarrely, the error only appears to happen when running `grunt csslint` in isolation - running it as part of a larger task does not cause the error.
